# .github/ISSUE_TEMPLATE/config.yml

blank_issues_enabled: false
contact_links:
  - name: Questions or Support
    url: https://github.com/amirahnasihah/standard-repo/discussions
    about: Please ask general questions or request help in Discussions instead of creating an issue.